#!/usr/bin/env bash
# ============================================================
# generate-env.sh — Generate .env with RSA keys for development
# Usage: bash scripts/generate-env.sh
# Compatible: macOS + Linux
# ============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  .env already exists — skipping (delete it first to regenerate)"
  exit 0
fi

echo "🔑 Generating RSA key pairs..."

# Helper: convert PEM to single-line with literal \n
pem_to_oneline() {
  # Replace actual newlines with literal \n, strip trailing \n
  echo "$1" | awk '{printf "%s\\n", $0}' | sed 's/\\n$//'
}

# Generate Access token RSA key pair
ACCESS_PRIVATE=$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)
ACCESS_PUBLIC=$(echo "$ACCESS_PRIVATE" | openssl pkey -pubout 2>/dev/null)
ACCESS_PRIVATE_LINE=$(pem_to_oneline "$ACCESS_PRIVATE")
ACCESS_PUBLIC_LINE=$(pem_to_oneline "$ACCESS_PUBLIC")

# Generate Refresh token RSA key pair
REFRESH_PRIVATE=$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)
REFRESH_PUBLIC=$(echo "$REFRESH_PRIVATE" | openssl pkey -pubout 2>/dev/null)
REFRESH_PRIVATE_LINE=$(pem_to_oneline "$REFRESH_PRIVATE")
REFRESH_PUBLIC_LINE=$(pem_to_oneline "$REFRESH_PUBLIC")

# Generate random secrets
FORGOT_SECRET=$(openssl rand -hex 32)
CONFIRM_SECRET=$(openssl rand -hex 32)

echo "✅ Keys generated"

cat > "$ENV_FILE" <<ENVEOF
# ============================================================
# Development .env — Generated by scripts/generate-env.sh
# DO NOT COMMIT THIS FILE
# ============================================================

# Database
DATABASE_URL=postgresql://postgres:postgres@postgres:5432/shop?schema=public

# Application
NODE_ENV=development
APP_PORT=3002
API_PREFIX=api
APP_FALLBACK_LANGUAGE=en
APP_HEADER_LANGUAGE=x-custom-lang
FRONTEND_DOMAIN=http://localhost:3000
BACKEND_DOMAIN=http://localhost:3002

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:3002

# Rate limiting
THROTTLE_TTL_MS=60000
THROTTLE_LIMIT=100

# JWT
AUTH_JWT_TOKEN_EXPIRES_IN=1d
AUTH_REFRESH_TOKEN_EXPIRES_IN=30d
AUTH_FORGOT_SECRET=${FORGOT_SECRET}
AUTH_FORGOT_TOKEN_EXPIRES_IN=1h
AUTH_CONFIRM_EMAIL_SECRET=${CONFIRM_SECRET}
AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN=1d

# Transactional email (Resend). Fill RESEND_API_KEY to enable delivery.
# Development/test can use Shop <onboarding@resend.dev>; production must use
# a sender from a verified Resend domain.
RESEND_API_KEY=
RESEND_FROM=Shop <onboarding@resend.dev>

# RSA Keys (auto-generated)
ACCESS_JWT_PRIVATE_KEY="${ACCESS_PRIVATE_LINE}"
ACCESS_JWT_PUBLIC_KEY="${ACCESS_PUBLIC_LINE}"
REFRESH_JWT_PRIVATE_KEY="${REFRESH_PRIVATE_LINE}"
REFRESH_JWT_PUBLIC_KEY="${REFRESH_PUBLIC_LINE}"

# WebAuthn
WEBAUTHN_RP_ID=localhost
WEBAUTHN_RP_NAME=ShopApp
WEBAUTHN_ALLOWED_ORIGINS=http://localhost:3002
WEBAUTHN_CHALLENGE_TTL_SEC=300

# Google OAuth (fill after ngrok setup)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=https://REPLACE_WITH_NGROK_URL/api/v1/auth/google/callback

# Cloudinary
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=

# MoMo Payment Sandbox
MOMO_PARTNER_CODE=MOMO_ATM_DEV
MOMO_ACCESS_KEY=
MOMO_SECRET_KEY=
MOMO_ENDPOINT=https://test-payment.momo.vn
MOMO_IPN_URL=https://REPLACE_WITH_NGROK_URL/api/v1/webhooks/momo
MOMO_REDIRECT_URL=http://localhost:3000/payment/return
MOMO_PAYMENT_EXPIRY_MINUTES=15

# Frontend
NEXT_PUBLIC_API_URL=http://localhost:3002/api

# ngrok (get token at https://dashboard.ngrok.com)
NGROK_AUTHTOKEN=
ENVEOF

echo ""
echo "✅ .env created at ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Fill GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET"
echo "  2. Fill CLOUDINARY_CLOUD_NAME / API_KEY / API_SECRET"
echo "  3. Fill RESEND_API_KEY to test transactional email"
echo "  4. Fill MOMO_ACCESS_KEY / MOMO_SECRET_KEY"
echo "  5. Optional: Fill NGROK_AUTHTOKEN for OAuth + MoMo IPN tunneling"
echo "  6. Run: make up"
