---
to: src/application/<%= name %>/README.md
---
# <%= h.changeCase.title(name) %> bounded context

Generated by `bun run generate:module` on <%= new Date().toISOString().split('T')[0] %>.

## Next steps

1. Add the `<%= sampleEntity %>` model to `prisma/schema.prisma` (snippet in
   `src/infrastructure/persistence/repositories/prisma-<%= h.changeCase.kebab(sampleEntity) %>.repository.ts`).
2. Generate + apply migration:
   ```bash
   bunx prisma migrate dev --name add_<%= h.changeCase.snake(sampleEntity) %>
   bunx prisma generate
   ```
3. Implement the Prisma repository methods (3 TODOs in
   `prisma-<%= h.changeCase.kebab(sampleEntity) %>.repository.ts`).
4. Register `<%= h.changeCase.pascal(name) %>Module` in `src/app.module.ts`:
   ```typescript
   import { <%= h.changeCase.pascal(name) %>Module } from './application/<%= name %>/<%= name %>.module';
   // ...
   imports: [..., <%= h.changeCase.pascal(name) %>Module],
   ```
5. Add tests (`src/application/<%= name %>/commands/**/*.handler.spec.ts`).

## Structure

```
src/application/<%= name %>/
├── <%= name %>.module.ts             # composition root
├── commands/
│   └── create-<%= h.changeCase.kebab(sampleEntity) %>/
│       ├── create-<%= h.changeCase.kebab(sampleEntity) %>.command.ts
│       ├── create-<%= h.changeCase.kebab(sampleEntity) %>.handler.ts
│       └── index.ts
├── queries/
│   └── get-<%= h.changeCase.kebab(sampleEntity) %>/
│       ├── get-<%= h.changeCase.kebab(sampleEntity) %>.query.ts
│       ├── get-<%= h.changeCase.kebab(sampleEntity) %>.handler.ts
│       └── index.ts
└── ports/
    └── <%= h.changeCase.kebab(sampleEntity) %>/
        ├── <%= h.changeCase.kebab(sampleEntity) %>.repository.port.ts
        └── <%= h.changeCase.kebab(sampleEntity) %>.repository.port.token.ts

src/domain/entities/<%= h.changeCase.kebab(sampleEntity) %>.ts
src/infrastructure/persistence/repositories/prisma-<%= h.changeCase.kebab(sampleEntity) %>.repository.ts
src/presentation/http/controllers/<%= name %>.controller.ts
```
